# Generated by Django 2.0.3 on 2018-04-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='img/sections/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='section.Section', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Subseção',
                'verbose_name_plural': 'Subseções',
            },
        ),
    ]
