# Generated by Django 2.0.3 on 2018-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='img/logos/', verbose_name='Logo')),
                ('location', models.CharField(max_length=40, verbose_name='Localização')),
                ('email', models.EmailField(max_length=250, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Fábrica Configuração',
                'verbose_name_plural': 'Fábrica Configurações',
            },
        ),
    ]
