# Generated by Django 2.0.3 on 2018-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=30, verbose_name='Classe do ícone')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('photo', models.ImageField(upload_to='img/members/', verbose_name='Foto')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('profession', models.CharField(max_length=35, verbose_name='Profissão')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('logo', models.ImageField(upload_to='img/portifolio/', verbose_name='Logo do Projeto')),
                ('status', models.CharField(choices=[('A', 'Em andamento'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
